[[headers]]
  for = "/*"
  [headers.values]
    # Allow Google Sign-In popups to work properly
    Cross-Origin-Opener-Policy = "same-origin-allow-popups"
    
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
